runfile('C:/Users/ldgar/OneDrive/Documentos/DataVisualizationQuiz/ProyectoIntegrador.ipy', wdir='C:/Users/ldgar/OneDrive/Documentos/DataVisualizationQuiz')
ERROR: Invalid requirement: '=='
Requirement already satisfied: gym in c:\users\ldgar\anaconda3\lib\site-packages (0.21.0)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\ldgar\anaconda3\lib\site-packages (from gym) (1.6.0)
Requirement already satisfied: numpy>=1.18.0 in c:\users\ldgar\anaconda3\lib\site-packages (from gym) (1.18.5)
Requirement already satisfied: keras in c:\users\ldgar\anaconda3\lib\site-packages (2.7.0)
Requirement already satisfied: keras-rl2 in c:\users\ldgar\appdata\roaming\python\python38\site-packages (1.0.5)
Requirement already satisfied: tensorflow in c:\users\ldgar\anaconda3\lib\site-packages (from keras-rl2) (2.3.0)
Requirement already satisfied: grpcio>=1.8.6 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.36.1)
Requirement already satisfied: astunparse==1.6.3 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.6.3)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.1.0)
Requirement already satisfied: tensorflow-estimator<2.4.0,>=2.3.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (2.3.0)
Requirement already satisfied: scipy==1.4.1 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.4.1)
Requirement already satisfied: tensorboard<3,>=2.3.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (2.4.0)
Requirement already satisfied: six>=1.12.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.15.0)
Requirement already satisfied: numpy<1.19.0,>=1.16.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.18.5)
Requirement already satisfied: h5py<2.11.0,>=2.10.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (2.10.0)
Requirement already satisfied: absl-py>=0.7.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (0.13.0)
Requirement already satisfied: protobuf>=3.9.2 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (3.17.2)
Requirement already satisfied: wrapt>=1.11.1 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.12.1)
Requirement already satisfied: keras-preprocessing<1.2,>=1.1.1 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (1.1.2)
Requirement already satisfied: wheel>=0.26 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (0.36.2)
Requirement already satisfied: google-pasta>=0.1.8 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (0.2.0)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorflow->keras-rl2) (3.3.0)
Requirement already satisfied: gast==0.3.3 in c:\users\ldgar\appdata\roaming\python\python38\site-packages (from tensorflow->keras-rl2) (0.3.3)
Requirement already satisfied: markdown>=2.6.8 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (3.3.4)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (0.4.4)
Requirement already satisfied: google-auth<2,>=1.6.3 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (1.21.3)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (1.6.0)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (1.0.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (52.0.0.post20210125)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\ldgar\anaconda3\lib\site-packages (from tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (2.25.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\ldgar\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (4.7.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\ldgar\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\ldgar\anaconda3\lib\site-packages (from google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (4.2.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\ldgar\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\ldgar\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (0.4.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ldgar\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (1.26.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ldgar\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\ldgar\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\ldgar\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (4.0.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\ldgar\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3,>=2.3.0->tensorflow->keras-rl2) (3.1.1)
Requirement already satisfied: gym[all] in c:\users\ldgar\anaconda3\lib\site-packages (0.21.0)
Requirement already satisfied: numpy>=1.18.0 in c:\users\ldgar\anaconda3\lib\site-packages (from gym[all]) (1.18.5)
Requirement already satisfied: cloudpickle>=1.2.0 in c:\users\ldgar\anaconda3\lib\site-packages (from gym[all]) (1.6.0)
Collecting box2d-py==2.3.5
  Using cached box2d-py-2.3.5.tar.gz (374 kB)
Collecting lz4>=3.1.0
  Using cached lz4-3.1.3-cp38-cp38-win_amd64.whl (192 kB)
Requirement already satisfied: opencv-python>=3. in c:\users\ldgar\anaconda3\lib\site-packages (from gym[all]) (4.5.4.58)
Requirement already satisfied: scipy>=1.4.1 in c:\users\ldgar\anaconda3\lib\site-packages (from gym[all]) (1.4.1)
Requirement already satisfied: pyglet>=1.4.0 in c:\users\ldgar\anaconda3\lib\site-packages (from gym[all]) (1.5.21)
Collecting mujoco-py<2.0,>=1.50
  Using cached mujoco-py-1.50.1.68.tar.gz (120 kB)
Collecting ale-py~=0.7.1
  Using cached ale_py-0.7.3-cp38-cp38-win_amd64.whl (925 kB)
Requirement already satisfied: importlib-resources in c:\users\ldgar\anaconda3\lib\site-packages (from ale-py~=0.7.1->gym[all]) (5.4.0)
Requirement already satisfied: glfw>=1.4.0 in c:\users\ldgar\anaconda3\lib\site-packages (from mujoco-py<2.0,>=1.50->gym[all]) (2.4.0)
Requirement already satisfied: Cython>=0.27.2 in c:\users\ldgar\anaconda3\lib\site-packages (from mujoco-py<2.0,>=1.50->gym[all]) (0.29.23)
Requirement already satisfied: imageio>=2.1.2 in c:\users\ldgar\anaconda3\lib\site-packages (from mujoco-py<2.0,>=1.50->gym[all]) (2.9.0)
Requirement already satisfied: cffi>=1.10 in c:\users\ldgar\anaconda3\lib\site-packages (from mujoco-py<2.0,>=1.50->gym[all]) (1.14.5)
Requirement already satisfied: lockfile>=0.12.2 in c:\users\ldgar\anaconda3\lib\site-packages (from mujoco-py<2.0,>=1.50->gym[all]) (0.12.2)
Requirement already satisfied: pycparser in c:\users\ldgar\anaconda3\lib\site-packages (from cffi>=1.10->mujoco-py<2.0,>=1.50->gym[all]) (2.20)
Requirement already satisfied: pillow in c:\users\ldgar\anaconda3\lib\site-packages (from imageio>=2.1.2->mujoco-py<2.0,>=1.50->gym[all]) (8.2.0)
Requirement already satisfied: zipp>=3.1.0 in c:\users\ldgar\anaconda3\lib\site-packages (from importlib-resources->ale-py~=0.7.1->gym[all]) (3.4.1)
Building wheels for collected packages: box2d-py, mujoco-py
  Building wheel for box2d-py (setup.py): started
  Building wheel for box2d-py (setup.py): finished with status 'error'
  Running setup.py clean for box2d-py
  Building wheel for mujoco-py (setup.py): started
  Building wheel for mujoco-py (setup.py): finished with status 'error'
  Running setup.py clean for mujoco-py
Failed to build box2d-py mujoco-py
Installing collected packages: mujoco-py, lz4, box2d-py, ale-py
    Running setup.py install for mujoco-py: started
    Running setup.py install for mujoco-py: finished with status 'error'
2
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ldgar\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\box2d-py_e7d05822609649e68591bcb9ed8e7a79\\setup.py'"'"'; __file__='"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\box2d-py_e7d05822609649e68591bcb9ed8e7a79\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ldgar\AppData\Local\Temp\pip-wheel-9xnqmshm'
       cwd: C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\box2d-py_e7d05822609649e68591bcb9ed8e7a79\
  Complete output (16 lines):
  Using setuptools (version 52.0.0.post20210125).
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\Box2D
  copying library\Box2D\Box2D.py -> build\lib.win-amd64-3.8\Box2D
  copying library\Box2D\__init__.py -> build\lib.win-amd64-3.8\Box2D
  creating build\lib.win-amd64-3.8\Box2D\b2
  copying library\Box2D\b2\__init__.py -> build\lib.win-amd64-3.8\Box2D\b2
  running build_ext
  building 'Box2D._Box2D' extension
  swigging Box2D\Box2D.i to Box2D\Box2D_wrap.cpp
  swig.exe -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library\Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D\Box2D_wrap.cpp Box2D\Box2D.i
  error: command 'swig.exe' failed: No such file or directory
  ----------------------------------------
  ERROR: Failed building wheel for box2d-py
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\ldgar\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\\setup.py'"'"'; __file__='"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ldgar\AppData\Local\Temp\pip-wheel-7bbj3p2r'
       cwd: C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\
  Complete output (54 lines):
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: C:\Users\ldgar\.mujoco\mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\setup.py", line 32, in <module>
      setup(
    File "C:\Users\ldgar\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\ldgar\anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\ldgar\anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\ldgar\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\ldgar\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\ldgar\anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\ldgar\anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\mujoco_py\__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\mujoco_py\builder.py", line 502, in <module>
      mjpro_path, key_path = discover_mujoco()
    File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\mujoco_py\utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: C:\Users\ldgar\.mujoco\mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ldgar\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\\setup.py'"'"'; __file__='"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ldgar\AppData\Local\Temp\pip-record-36aydjt8\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ldgar\anaconda3\Include\mujoco-py'
         cwd: C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\
    Complete output (56 lines):
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: C:\Users\ldgar\.mujoco\mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\setup.py", line 32, in <module>
        setup(
      File "C:\Users\ldgar\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\ldgar\anaconda3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\ldgar\anaconda3\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\ldgar\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ldgar\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\ldgar\anaconda3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\ldgar\anaconda3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\ldgar\anaconda3\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\mujoco_py\__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\mujoco_py\builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "C:\Users\ldgar\AppData\Local\Temp\pip-install-g0oaiyg8\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\mujoco_py\utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: C:\Users\ldgar\.mujoco\mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\ldgar\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\\setup.py'"'"'; __file__='"'"'C:\\Users\\ldgar\\AppData\\Local\\Temp\\pip-install-g0oaiyg8\\mujoco-py_7e75f00cf4224e9ca84c7986786dba2c\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ldgar\AppData\Local\Temp\pip-record-36aydjt8\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\ldgar\anaconda3\Include\mujoco-py' Check the logs for full command output.
Episode:1 Score35.0
Episode:2 Score20.0
Episode:3 Score46.0
Episode:4 Score23.0
Episode:5 Score12.0
Episode:6 Score38.0
Episode:7 Score20.0
Episode:8 Score20.0
Episode:9 Score25.0
Episode:10 Score14.0
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
flatten_2 (Flatten)          (None, 4)                 0         
_________________________________________________________________
dense_4 (Dense)              (None, 24)                120       
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 50        
=================================================================
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________
Training for 50000 steps ...
Interval 1 (0 steps performed)
WARNING:tensorflow:From C:\Users\ldgar\anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_v1.py:2070: Model.state_updates (from tensorflow.python.keras.engine.training) is deprecated and will be removed in a future version.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
    1/10000 [..............................] - ETA: 1:02:19 - reward: 1.0000C:\Users\ldgar\AppData\Roaming\Python\Python38\site-packages\rl\memory.py:37: UserWarning: Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!
  warnings.warn('Not enough entries to sample without replacement. Consider increasing your warm-up phase to avoid oversampling!')
10000/10000 [==============================] - 133s 13ms/step - reward: 1.0000030/10000 [==========================>...] - ETA: 12s - reward: 1.0000
138 episodes - episode_reward: 71.543 [9.000, 200.000] - loss: 5.697 - mae: 15.014 - mean_q: 29.924

Interval 2 (10000 steps performed)
 7302/10000 [====================>.........] - ETA: 34s - reward: 1.0000  - ETA: 1:26 - reward: 1.0000Exception ignored in: <function Viewer.__del__ at 0x000001A7FCD90280>
Traceback (most recent call last):
  File "C:\Users\ldgar\anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 185, in __del__
    self.close()
  File "C:\Users\ldgar\anaconda3\lib\site-packages\gym\envs\classic_control\rendering.py", line 101, in close
    self.window.close()
  File "C:\Users\ldgar\anaconda3\lib\site-packages\pyglet\window\win32\__init__.py", line 328, in close
    super(Win32Window, self).close()
  File "C:\Users\ldgar\anaconda3\lib\site-packages\pyglet\window\__init__.py", line 857, in close
    app.windows.remove(self)
  File "C:\Users\ldgar\anaconda3\lib\_weakrefset.py", line 109, in remove
    self.data.remove(ref(item))
KeyError: <weakref at 0x000001A7FCD8BEF0; to 'Win32Window' at 0x000001A7FC986130>
10000/10000 [==============================] - 131s 13ms/step - reward: 1.0000
50 episodes - episode_reward: 200.000 [200.000, 200.000] - loss: 16.240 - mae: 34.882 - mean_q: 70.343

Interval 3 (20000 steps performed)
10000/10000 [==============================] - 133s 13ms/step - reward: 1.0000/10000 [==>...........................] - ETA: 1:57 - reward: 1.0000 8373/10000 [========================>.....] - ETA: 21s - reward: 1.0000
50 episodes - episode_reward: 200.000 [200.000, 200.000] - loss: 19.656 - mae: 42.354 - mean_q: 85.396

Interval 4 (30000 steps performed)
10000/10000 [==============================] - 151s 15ms/step - reward: 1.0000/10000 [=========================>....] - ETA: 17s - reward: 1.0000
50 episodes - episode_reward: 200.000 [200.000, 200.000] - loss: 19.293 - mae: 44.132 - mean_q: 88.848

Interval 5 (40000 steps performed)
10000/10000 [==============================] - 158s 16ms/step - reward: 1.0000A: 1:58 - reward: 1.0000
done, took 705.312 seconds
Testing for 100 episodes ...
Episode 1: reward: 200.000, steps: 200
Episode 2: reward: 200.000, steps: 200
Episode 3: reward: 200.000, steps: 200
Episode 4: reward: 200.000, steps: 200
Episode 5: reward: 200.000, steps: 200
Episode 6: reward: 200.000, steps: 200
Episode 7: reward: 200.000, steps: 200
Episode 8: reward: 200.000, steps: 200
Episode 9: reward: 200.000, steps: 200
Episode 10: reward: 200.000, steps: 200
Episode 11: reward: 200.000, steps: 200
Episode 12: reward: 200.000, steps: 200
Episode 13: reward: 200.000, steps: 200
Episode 14: reward: 200.000, steps: 200
Episode 15: reward: 200.000, steps: 200
Episode 16: reward: 200.000, steps: 200
Episode 17: reward: 200.000, steps: 200
Episode 18: reward: 200.000, steps: 200
Episode 19: reward: 200.000, steps: 200
Episode 20: reward: 200.000, steps: 200
Episode 21: reward: 200.000, steps: 200
Episode 22: reward: 200.000, steps: 200
Episode 23: reward: 200.000, steps: 200
Episode 24: reward: 200.000, steps: 200
Episode 25: reward: 200.000, steps: 200
Episode 26: reward: 200.000, steps: 200
Episode 27: reward: 200.000, steps: 200
Episode 28: reward: 200.000, steps: 200
Episode 29: reward: 200.000, steps: 200
Episode 30: reward: 200.000, steps: 200
Episode 31: reward: 200.000, steps: 200
Episode 32: reward: 200.000, steps: 200
Episode 33: reward: 200.000, steps: 200
Episode 34: reward: 200.000, steps: 200
Episode 35: reward: 200.000, steps: 200
Episode 36: reward: 200.000, steps: 200
Episode 37: reward: 200.000, steps: 200
Episode 38: reward: 200.000, steps: 200
Episode 39: reward: 200.000, steps: 200
Episode 40: reward: 200.000, steps: 200
Episode 41: reward: 200.000, steps: 200
Episode 42: reward: 200.000, steps: 200
Episode 43: reward: 200.000, steps: 200
Episode 44: reward: 200.000, steps: 200
Episode 45: reward: 200.000, steps: 200
Episode 46: reward: 200.000, steps: 200
Episode 47: reward: 200.000, steps: 200
Episode 48: reward: 200.000, steps: 200
Episode 49: reward: 200.000, steps: 200
Episode 50: reward: 200.000, steps: 200
Episode 51: reward: 200.000, steps: 200
Episode 52: reward: 200.000, steps: 200
Episode 53: reward: 200.000, steps: 200
Episode 54: reward: 200.000, steps: 200
Episode 55: reward: 200.000, steps: 200
Episode 56: reward: 200.000, steps: 200
Episode 57: reward: 200.000, steps: 200
Episode 58: reward: 200.000, steps: 200
Episode 59: reward: 200.000, steps: 200
Episode 60: reward: 200.000, steps: 200
Episode 61: reward: 200.000, steps: 200
Episode 62: reward: 200.000, steps: 200
Episode 63: reward: 200.000, steps: 200
Episode 64: reward: 200.000, steps: 200
Episode 65: reward: 200.000, steps: 200
Episode 66: reward: 200.000, steps: 200
Episode 67: reward: 200.000, steps: 200
Episode 68: reward: 200.000, steps: 200
Episode 69: reward: 200.000, steps: 200
Episode 70: reward: 200.000, steps: 200
Episode 71: reward: 200.000, steps: 200
Episode 72: reward: 200.000, steps: 200
Episode 73: reward: 200.000, steps: 200
Episode 74: reward: 200.000, steps: 200
Episode 75: reward: 200.000, steps: 200
Episode 76: reward: 200.000, steps: 200
Episode 77: reward: 200.000, steps: 200
Episode 78: reward: 200.000, steps: 200
Episode 79: reward: 200.000, steps: 200
Episode 80: reward: 200.000, steps: 200
Episode 81: reward: 200.000, steps: 200
Episode 82: reward: 200.000, steps: 200
Episode 83: reward: 200.000, steps: 200
Episode 84: reward: 200.000, steps: 200
Episode 85: reward: 200.000, steps: 200
Episode 86: reward: 200.000, steps: 200
Episode 87: reward: 200.000, steps: 200
Episode 88: reward: 200.000, steps: 200
Episode 89: reward: 200.000, steps: 200
Episode 90: reward: 200.000, steps: 200
Episode 91: reward: 200.000, steps: 200
Episode 92: reward: 200.000, steps: 200
Episode 93: reward: 200.000, steps: 200
Episode 94: reward: 200.000, steps: 200
Episode 95: reward: 200.000, steps: 200
Episode 96: reward: 200.000, steps: 200
Episode 97: reward: 200.000, steps: 200
Episode 98: reward: 200.000, steps: 200
Episode 99: reward: 200.000, steps: 200
Episode 100: reward: 200.000, steps: 200
200.0
Testing for 5 episodes ...
Episode 1: reward: 200.000, steps: 200
Episode 2: reward: 200.000, steps: 200
Episode 3: reward: 200.000, steps: 200
Episode 4: reward: 200.000, steps: 200
Episode 5: reward: 200.000, steps: 200
